### ISSUE TITLE
v1.3.0 being blocked by AirLock Agent

### ISSUE THREAD

**Issue by djlongy** [cmdwtf/KeePassDiceware#11]
Not a massive issue but for some reason version 1.3 and also the b1 beta is being picked up and blocked by AirLock app whitelisting.
Funnily enough v1.2.1 works just completely fine.
It must be detecting some code that it thinks is malicious from version 1.2.1 to version 1.3.

**Comment by nitz** [comment]
Hmm. That's odd. I do think I updated my tooling since 1.21, but the actual code hasn't changed that much. I'll check to see if maybe an inherited dependency changed or something else that might have upset it.

By any chance, do you have a .NET development environment that you could try building the plug-in with? I'm curious if it's something that would get picked up if it was built locally.

**Comment by djlongy** [comment]
I think it's just corporate policy and them hashing and whitelisting all existing libraries that are allowed to run.
Not sure if there's anything you can do from your end.
I think this can be closed.
