### ISSUE TITLE
Is exact version dependency obligatory?

### ISSUE THREAD

**Issue by viciousvex** [cmdwtf/KeePassDiceware#14]
Hi Chris,

first of all thanks for your wonderful plugin and work! I wondered why KeePass didn't have a built-in diceware password generator. I think these are the "best" passwords one can get.

I was having problems starting the plugin with KeePass 2.50 and got this error message:
![KeePass](https://user-images.githubusercontent.com/1662172/183647949-33ad06fc-17b2-48c1-91ca-7dc808e1bc9e.png)

After upgrading to 2.51.1 the plugin worked. Is your plugin targeted to work with a very specific build only, or is it compatible with a range of versions?

Regards

**Comment by nitz** [comment]
Hi!

So, I built the binaries uploaded here against 2.51.1, just because that's what was on my machine at the time. I don't think there's any particular dependencies on that (or any specific) version, so it may be as simple as a manifest that specifies a range it'll be compatible with. I'll look into if there's a way to specify that. (There's a very odd 'circular' dependency the way the plugin depends on the application that's loading it like that, but it's also the cool way that KeePass lets the whole app function as the SDK for plugins!)

In the meantime; If you have a build environment, you should be able to build it against 2.50.x manually and I believe everything should work the same.

**Comment by viciousvex** [comment]
Wow. Thanks for your faster-than-light answer!
