### ISSUE TITLE
Word list licensing terms missing

### ISSUE THREAD

**Issue by pomeloy** [cmdwtf/KeePassDiceware#21]
The licensing terms for the diceware word lists are missing. Is there a way to add comments to the plain-text files while still allowing the application to be built correctly?

**Comment by nitz** [comment]
The wordlists are from [Strongbox](https://github.com/strongbox-password-safe/Strongbox/tree/master/resources/wordlists) which is AGPL-3.0 licensed, which is where this project inherits it's license from. Is there a particular reason you feel the wordlists need the license terms mentioned in them specifically?

(I'm going to close this issue for now, but we can keep discussing here!)

**Comment by nitz** [comment]
So I'm reading the `How to Apply These Terms to Your New Program` section of the [license](https://github.com/cmdwtf/KeePassDiceware/blob/main/LICENSE#L627-L630), particularly this:

>  To do so, attach the following notices to the program.  It is safest
to attach them to the start of each source file to most effectively
state the exclusion of warranty; and each file should have at least
the "copyright" line and a pointer to where the full notice is found.

My understanding of how that's written is that while it is "safest" to put them in the start of each source file, it's not required. 

If the changes you want to propose are from MIT licensed works, that should be fine since MIT is "GPL-compatible" ([info](https://www.gnu.org/licenses/gpl-faq.html#WhatDoesCompatMean)). 

If you'd like, we could add a note that those changes in particular came from MIT licensed works, similar to how I mention `[Microsoft.SourceLink.Git](https://github.com/dotnet/sourcelink)`.

**Comment by pomeloy** [comment]
Thanks for the quick response. As you already replied to #22 you are most likely aware of the reason I opened this issue. I only stumbled upon the licensing terms during my search for a better German word list. 

The original diceware word list is licensed as follows:
[http://world.std.com/~reinhold/dicewarewordlist.pdf](http://world.std.com/~reinhold/dicewarewordlist.pdf)
> "The author hereby grants rights for free, non-commercial, distribution of this entire text with attribution. All other rights reserved." 
It may be reasonable to put these remarks into your license section.

Strongbox merely uses (and mentions using) the word lists from https://github.com/micahflee/passphrases which in turn does not specify their origin.

**Comment by nitz** [comment]
Oh now this is getting quite interesting. (Licensing & Intellectual Property is something I'm quite interested in, so discussions like this are always welcome for me!)

So the license in Reinhold's pdf you linked says exactly what you quoted. What's interesting though, is that particular work includes not only the word list, but also corresponding dice roll values. (It also includes brief Diceware instructions.) The license also specifies the *entire* text, of which neither @micahflee, nor any of us using it downstream are actually using. Rather, our lists are _only_ a list of words, with neither the "dice rolls" nor instructions.

Reinhold also [publishes another list](https://theworld.com/%7Ereinhold/diceware.wordlist.asc), linked from [his Diceware page](https://theworld.com/~reinhold/diceware.html) that includes only the words and dice rolls (and a PGP signature.) I imagine that _may_ have been the original work that was modified by micahflee for their project. (that's speculation on my part.) Reinhold mentions at the bottom of his Diceware page, that:

> To the extent that a word list is protected by copyright, A G Reinhold licenses its rights to the English Diceware Wordlist under the [Creative Commons CC-BY ](http://creativecommons.org/licenses/by/4.0/)[4.0](http://creativecommons.org/licenses/by/4.0/) license.

I'm certainly missing a bit of complying with that license (while I'm [crediting](https://github.com/cmdwtf/KeePassDiceware/blob/main/WordLists.cs#L33), I'm missing the copyright/license notice and link to the license.

As it seems Reinhold is quite responsive, I've decided to reach out to him to ask how he'd prefer to be acknowledged, and his opinion on the matter.

**Comment by pomeloy** [comment]
I just issued a pull request with my take on the compliance requirements right before you replied. Keep us updated on Reinhold's reply!
