### ISSUE TITLE
Don't run on Keepass 2.54

### ISSUE THREAD

**Issue by WWoodpecker** [cmdwtf/KeePassDiceware#30]
Unfortunately, the DLL does not work with Keepass 2.54. It seems to require version 2.53.1.20815. I get this error message when I start Keepass:

```
[Window Title]
KeePass

[Content]
The following plugin is incompatible with the current KeePass version:
...\Plugins\KeePassDiceware.dll

Have a look at the plugin's website for an appropriate version.

[Expanded Information]
Die Datei oder Assembly "KeePass, Version=2.53.1.20815, Culture=neutral, PublicKeyToken=fed2ed7716aecf5c" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
mscorlib
   bei System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   bei System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   bei System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   bei KeePass.Plugins.PluginManager.CreatePluginInstance(String strFilePath, String strTypeName) in W:\w\214de12e4e7c8ca6\KeePass\Plugins\PluginManager.cs:Zeile 296.
   bei KeePass.Plugins.PluginManager.LoadPlugins(List`1 lFiles, String strTypeName, String strDisplayFilePath, Boolean bSkipCacheFiles) in W:\w\214de12e4e7c8ca6\KeePass\Plugins\PluginManager.cs:Zeile 206.
Void GetType(System.Reflection.RuntimeAssembly, System.String, Boolean, Boolean, System.Runtime.CompilerServices.ObjectHandleOnStack)

[^] Details  [OK]

```
Does the DLL simply not run under 2.54, due to some functions that Keepass does not provide in a newer version, or has 2.5.3.1.20815 simply been hard-coded by mistake?

Greetings

**Comment by nitz** [comment]
Hmm, this seems like the same thing as #14. I added an assembly binding in 5d4bb876e8377f8cd4efd3d2cd58c1794716856a for that, but I hadn't adjusted it since. I'm currently running KeePass v2.57 with the KeePassDiceware v1.6 and haven't encountered any issues.

Do you see the same issue if you try running it with a more recent version of KeePass? As it stands, I'm unfortunately unable to reproduce this issue, and am not sure what external factors might be contributing to it.

**Comment by WWoodpecker** [comment]
Hi,

unfortunately it is not possible for me to integrate a newer version of Keepass, as we have a customised version with a password server connection. This means that we can only use the customised Keepass version from the password server manufacturer. :(
I have also just tested it with an original Keepass 2.54 and it works... OK, so I guess we can't use the plugin, what a pity. :(
I would like that very much, especially if you have a German dictionary in your plugin ^^

**Comment by nitz** [comment]
That explains it! Turns out it's not the version at all :) And you may still be able to use it if you're willing to make your own build.

Okay so that assembly binding I mentioned before is to bind *specifically* the official version KeePass, which is strongly signed with a public key token of `fed2ed7716aecf5c`. Your customized build not being signed with that prevents it from dynamically binding. If you were to build KeePassDiceware against your customized KeePass, it would likely work. (The removal or edit of the assembly binding in the `app.config` would need to happen as well, I'd guess.)

It might be worth asking your vendor if they can incorporate KeePassDiceware directly too. The license definitely allows for that!

**Comment by WWoodpecker** [comment]
OK, thank you very much.
Unfortunately, I didn't have the idea to test this with a standard Keepass ^^
I'll see if I can manage to build it myself... My programming skills are limited to simple scripts ^^

Thanks again.

**Comment by leftdisconnected** [comment]
Hello.  I am running a standard install of KeePass 2.57 (latest) and the plugin initially would not compile for me, showing similar errors to what was originally reported by WWoodpecker.

**However**, I resolved the problem by restoring the DLL to its original name of "KeePassDiceware.dll".  This was my fault as I had forgotten that PLGX files can be named as desired, but DLL's must remain as originally named.

Just a reminder so anyone reading this thread that the DLL should be used as-is.
